/** Demo document shown on first install and by the viewer's "Sample" button. */
export const WELCOME_DOCUMENT = [
  '---',
  'title: Usher',
  'subtitle: Markdown and Mermaid, everywhere',
  'tags: [markdown, mermaid, extension]',
  '---',
  '',
  '# Usher',
  '',
  'Usher renders Markdown from **local files**, **web pages**, and anything you **paste or drop** here.',
  '',
  '> [!NOTE]',
  '> Local `file://` documents need one extra opt-in: open the extension details page and enable',
  '> **Allow access to file URLs**.',
  '',
  '## What it handles',
  '',
  '| Feature | Notes |',
  '| --- | --- |',
  '| GitHub Flavored Markdown | Tables, task lists, strikethrough, autolinks |',
  '| Mermaid | Flowcharts, sequence, class, state, ER, gantt, pie, journey |',
  '| Syntax highlighting | 35+ languages including PowerShell, SQL, and C# |',
  '| Front matter | YAML shown as a table, TOML left alone |',
  '| Alerts | `[!NOTE]`, `[!TIP]`, `[!IMPORTANT]`, `[!WARNING]`, `[!CAUTION]` |',
  '| Math | `$…$` and `$$…$$` via KaTeX (off by default) |',
  '',
  '## Mermaid',
  '',
  'Fence a diagram with `mermaid` and it renders inline. Ctrl + scroll to zoom, drag to pan,',
  'double-click to reset.',
  '',
  '```mermaid',
  'flowchart LR',
  '    A[Local .md file] --> D{Usher}',
  '    B[Web page] --> D',
  '    C[Paste or drop] --> D',
  '    D --> E[Rendered HTML]',
  '    D --> F[Mermaid diagrams]',
  '    D --> G[Highlighted code]',
  '```',
  '',
  '```mermaid',
  'sequenceDiagram',
  '    participant P as Page',
  '    participant D as Detector',
  '    participant W as Service worker',
  '    participant R as Renderer',
  '    P->>D: document loaded',
  '    D->>D: is this Markdown?',
  '    D->>W: render request',
  '    W->>R: inject renderer',
  '    R->>P: replace body with rendered view',
  '```',
  '',
  '## Code',
  '',
  '```powershell',
  '$files = Get-ChildItem -Path . -Filter *.md -Recurse',
  'foreach ($file in $files) {',
  '    Write-Host "Found $($file.FullName)"',
  '}',
  '```',
  '',
  '```csharp',
  'public sealed class Renderer',
  '{',
  '    public string Render(string markdown) => Pipeline.Run(markdown);',
  '}',
  '```',
  '',
  '## Lists',
  '',
  '- [x] Render local files',
  '- [x] Render web pages',
  '- [x] Mermaid diagrams',
  '- [ ] Your document',
  '',
  '1. Open a `.md` file',
  '2. Usher takes over the tab',
  '3. Press `t` for contents, `r` for the raw source',
  '',
  '## Alerts',
  '',
  '> [!TIP]',
  '> Press `r` to flip between the rendered view and the original Markdown source.',
  '',
  '> [!WARNING]',
  '> Smart detection mode inspects every plain-text page. Extension-only mode is the safer default.',
  '',
  '---',
  '',
  'Definition lists, footnotes[^1], and `inline code` all work too.',
  '',
  'Term',
  ':   Its definition.',
  '',
  '[^1]: Footnotes land at the bottom with a link back.',
  '',
].join('\n');
