#!/usr/bin/env node
// Generates THIRD-PARTY-NOTICES.txt for the packages actually bundled into the shipped
// extension. The build sets esbuild's legalComments to 'none', which strips every upstream
// licence header, so without this file the package would redistribute MIT, BSD, ISC, and
// Apache-2.0 code with no attribution at all.
//
// The package list comes from esbuild's metafile, so it is exactly what ended up in the
// bundles -- not the declared dependency tree, which for mermaid includes a large number of
// @types/* packages that contribute no code.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { licenseTextOf, resolveLicense } from './lib/licenses.mjs';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const NODE_MODULES = join(ROOT, 'node_modules');
const METAFILE = join(ROOT, 'build', 'metafile.json');

function readManifest(name) {
  const file = join(NODE_MODULES, name, 'package.json');
  if (!existsSync(file)) {
    return null;
  }
  try {
    return JSON.parse(readFileSync(file, 'utf8'));
  } catch {
    return null;
  }
}

/** Package name from a bundler input path such as `node_modules/@scope/name/dist/x.js`. */
function packageNameFrom(inputPath) {
  const marker = inputPath.lastIndexOf('node_modules/');
  if (marker === -1) {
    return null;
  }
  const parts = inputPath.slice(marker + 'node_modules/'.length).split('/');
  if (parts.length === 0) {
    return null;
  }
  return parts[0].startsWith('@') && parts.length > 1 ? `${parts[0]}/${parts[1]}` : parts[0];
}

/** Exact set of third-party packages whose code reached the output bundles. */
function bundledPackages() {
  if (!existsSync(METAFILE)) {
    console.error(`Missing ${METAFILE}. Run "npm run build" first -- notices are derived from it.`);
    process.exit(1);
  }
  const meta = JSON.parse(readFileSync(METAFILE, 'utf8'));
  const names = new Set();
  for (const input of Object.keys(meta.inputs ?? {})) {
    const name = packageNameFrom(input.replace(/\\/g, '/'));
    if (name) {
      names.add(name);
    }
  }
  return [...names].sort();
}

function authorOf(pkg) {
  const author = pkg.author;
  if (typeof author === 'string') return author;
  if (author && typeof author === 'object' && author.name) {
    return author.email ? `${author.name} <${author.email}>` : author.name;
  }
  return '';
}

const rootManifest = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
const names = bundledPackages();

const missingText = [];
const entries = [];
for (const name of names) {
  const pkg = readManifest(name);
  if (!pkg) {
    missingText.push(`${name} (not installed)`);
    continue;
  }
  const dir = join(NODE_MODULES, name);
  const { license } = resolveLicense(pkg, dir);
  const text = licenseTextOf(dir);
  if (!text) {
    missingText.push(name);
  }
  entries.push({ name, version: pkg.version ?? '?', license: license || 'UNKNOWN', pkg, text });
}

const lines = [];
lines.push('THIRD-PARTY NOTICES FOR USHER');
lines.push('');
lines.push(`Usher ${rootManifest.version} bundles the open source packages listed below. Each package`);
lines.push('remains under its own licence; the full text of every licence follows the summary.');
lines.push('');
lines.push(`Generated by scripts/gen-notices.mjs from the build metafile (${entries.length} packages).`);
lines.push('');
lines.push('SUMMARY');
lines.push('');
const width = Math.max(...entries.map((entry) => entry.name.length));
for (const entry of entries) {
  lines.push(`  ${entry.name.padEnd(width)}  ${entry.version.padEnd(12)}  ${entry.license}`);
}
lines.push('');

for (const entry of entries) {
  lines.push('='.repeat(78));
  lines.push(`${entry.name} ${entry.version}`);
  lines.push(`Licence: ${entry.license}`);
  if (authorOf(entry.pkg)) {
    lines.push(`Author: ${authorOf(entry.pkg)}`);
  }
  if (entry.pkg.homepage) {
    lines.push(`Homepage: ${entry.pkg.homepage}`);
  }
  lines.push('='.repeat(78));
  lines.push('');
  lines.push(entry.text ?? `No licence file was shipped with this package. Declared licence: ${entry.license}.`);
  lines.push('');
}

const content = `${lines.join('\n')}\n`;
writeFileSync(join(ROOT, 'THIRD-PARTY-NOTICES.txt'), content);

const dist = join(ROOT, 'dist');
mkdirSync(dist, { recursive: true });
writeFileSync(join(dist, 'THIRD-PARTY-NOTICES.txt'), content);

console.log(`Wrote THIRD-PARTY-NOTICES.txt for ${entries.length} bundled packages.`);
const unknown = entries.filter((entry) => entry.license === 'UNKNOWN');
if (unknown.length > 0) {
  console.error(`FAILED: no licence could be resolved for ${unknown.map((entry) => entry.name).join(', ')}`);
  process.exit(1);
}
if (missingText.length > 0) {
  console.warn(`Note: no licence file shipped by ${missingText.join(', ')}; declared licence recorded instead.`);
}
