#!/usr/bin/env node
// Uploads the packaged extension to Microsoft Edge Add-ons and publishes it, using the
// Partner Center Update REST API v1.1.
//
//   node scripts/publish-edge.mjs [--no-publish]
//
// Requires three environment variables, taken from Partner Center > Publish API:
//   EDGE_PRODUCT_ID   the product this extension was first submitted as
//   EDGE_CLIENT_ID    the client id shown next to the API key
//   EDGE_API_KEY      the API key itself
//
// The first submission cannot be automated: a product has to exist before it has an id,
// so version 1.0.0 goes up by hand through Partner Center. Everything after that can run
// from CI. Note that API keys expire every 72 days and have to be regenerated by hand.
import { existsSync, readFileSync, statSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const BASE = 'https://api.addons.microsoftedge.microsoft.com/v1';
const POLL_INTERVAL_MS = 10000;
const POLL_TIMEOUT_MS = 15 * 60 * 1000;

const productId = process.env.EDGE_PRODUCT_ID;
const clientId = process.env.EDGE_CLIENT_ID;
const apiKey = process.env.EDGE_API_KEY;
const publishAfterUpload = !process.argv.includes('--no-publish');

if (!productId || !clientId || !apiKey) {
  console.error('Missing EDGE_PRODUCT_ID, EDGE_CLIENT_ID, or EDGE_API_KEY.');
  process.exit(1);
}

const version = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')).version;
const packagePath = join(ROOT, 'artifacts', `usher-${version}.zip`);
if (!existsSync(packagePath)) {
  console.error(`${packagePath} is missing. Run "npm run pack" first.`);
  process.exit(1);
}

const headers = { Authorization: `ApiKey ${apiKey}`, 'X-ClientID': clientId };

async function request(path, options = {}) {
  const response = await fetch(`${BASE}${path}`, { ...options, headers: { ...headers, ...options.headers } });
  const text = await response.text();
  return { status: response.status, headers: response.headers, text };
}

/** The upload and publish calls are asynchronous: both hand back an operation to poll. */
async function waitForOperation(path, label) {
  const deadline = Date.now() + POLL_TIMEOUT_MS;
  while (Date.now() < deadline) {
    await new Promise((done) => setTimeout(done, POLL_INTERVAL_MS));
    const { status, text } = await request(path);
    if (status !== 200) {
      throw new Error(`${label}: status check returned ${status} -- ${text.slice(0, 300)}`);
    }
    let body;
    try {
      body = JSON.parse(text);
    } catch {
      throw new Error(`${label}: could not parse status response -- ${text.slice(0, 300)}`);
    }
    if (body.status === 'InProgress') {
      process.stdout.write('.');
      continue;
    }
    process.stdout.write('\n');
    if (body.status === 'Succeeded') {
      return body;
    }
    throw new Error(`${label} failed: ${body.message ?? body.status}\n${JSON.stringify(body.errors ?? [], null, 2)}`);
  }
  throw new Error(`${label}: timed out after ${POLL_TIMEOUT_MS / 60000} minutes`);
}

const sizeMb = (statSync(packagePath).size / 1024 / 1024).toFixed(2);
console.log(`Uploading usher-${version}.zip (${sizeMb} MB) to product ${productId}`);

const upload = await request(`/products/${productId}/submissions/draft/package`, {
  method: 'POST',
  headers: { 'Content-Type': 'application/zip' },
  body: readFileSync(packagePath),
});
if (upload.status !== 202) {
  console.error(`Upload rejected with status ${upload.status}: ${upload.text.slice(0, 500)}`);
  process.exit(1);
}
const uploadOperation = upload.headers.get('location');
if (!uploadOperation) {
  console.error('Upload accepted but no operation id was returned.');
  process.exit(1);
}
console.log('Upload accepted, waiting for validation');
await waitForOperation(`/products/${productId}/submissions/draft/package/operations/${uploadOperation}`, 'Package upload');
console.log('Package validated.');

if (!publishAfterUpload) {
  console.log('Stopping before publish, as asked. The draft is ready in Partner Center.');
  process.exit(0);
}

const publish = await request(`/products/${productId}/submissions`, {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({ notes: `Usher ${version}` }),
});
if (publish.status !== 202) {
  console.error(`Publish rejected with status ${publish.status}: ${publish.text.slice(0, 500)}`);
  process.exit(1);
}
const publishOperation = publish.headers.get('location');
console.log('Publish accepted, waiting for it to be queued for review');
await waitForOperation(`/products/${productId}/submissions/operations/${publishOperation}`, 'Publish');
console.log(`Usher ${version} submitted for certification.`);
